language: php

sudo: false

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/phpunit
